version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - ".pg-data:/var/lib/postgresql/data"